### PR TITLE
fix special token not tokenized correctly, closes #5

### LINKED ISSUE #5: U+00B4 not correclty tokenized
Hello,

Just like described in the title, the unicode character “´” (U+00B4) is not correctly tokenized.

```
var vocab_path = TestUtils.DownloadFileToCache("https://cdn.huggingface.co/xlm-roberta-large-finetuned-conll03-english-sentencepiece.bpe.model");
var xlm_roberta_tokenizer = new XLMRobertaTokenizer(vocab_path, false);
var original_string = "´";

var expected_result = new TokenizedInput
{
    TokenIds = new List<long> { 0, 3309, 2},
    SpecialTokensMask = new List<byte> { },
    OverflowingTokens = new List<long>(),
    NumTruncatedTokens = 0,
    TokenOffsets = new List<Offset?> {
      null,
        new Offset(0,  1 ),
      null,
    },
    ReferenceOffsets = new List<List<uint>>(),
    Mask = new List<Mask> { }
};

// When
var result = xlm_roberta_tokenizer.Encode(xlm_roberta_tokenizer, original_string, null, 5, TruncationStrategy.OnlyFirst, 0);

// Then
Assert.Equal(expected_result.TokenIds, result.TokenIds);
Assert.Equal(expected_result.TokenOffsets, result.TokenOffsets);
```

### PR DESCRIPTION
**Pull request by EslaMx7**

### CODE REVIEW

File: src/Lokad.Tokenizers/Tokenizer/TokenizationUtils.cs [hunk 1]
```diff
@@ -410,7 +410,7 @@ public static void DecomposeNfkc(Token token)
 
             //HINT: [@eslam] check if character is removed from the original text after normalization
             if (!token.Text.EnumerateRunes().Contains(character))
-                extraCharSize = -1;
+                extraCharSize -= character.Utf8SequenceLength - character.Utf16SequenceLength;// -1;
```
Comment (ClementLokad) [inline src/Lokad.Tokenizers/Tokenizer/TokenizationUtils.cs]: I think it would be better to have a nkfc enumerator that returns the characters and the extra characters count values to avoid any additional processing (https://github.com/guillaume-be/rust-tokenizers/blob/main/main/src/tokenizer/tokenization_utils.rs#L215)

**Review by ClementLokad — CHANGES_REQUESTED** [review]
https://github.com/Lokad/Tokenizers/pull/7#discussion_r1591199889

File: src/Lokad.Tokenizers/Tokenizer/TokenizationUtils.cs (hunk 1 above)
Comment (EslaMx7) [reply src/Lokad.Tokenizers/Tokenizer/TokenizationUtils.cs]: Agree, PR updated.
